version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'yourStrong(!)Password'
    ports: 
      - '5526:1433'
    volumes: 
      - data:/var/opt/mssql
  api:
    build: .
    ports:
      - '3022:80'
    depends_on:
      - db
volumes:
  data: